pipeline {
    agent any

    stages {
        stage('Patch') {
            steps {
                cd vms/data/chem2vec
                sed -i -E "s/num_latent = [0-9]+/num_latent = $NUM_LATENT/g" options.ini
                sed -i -E "s/nsamples = [0-9]+/nsamples = $NUM_LATENT/g" options.ini
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}