
CFLAGS_      = $(CFLAGS) -O1 -std=c++11 
MCXX_FLAGS_   = --ompss --variable=disable_final_clause_transformation:1 
MCXX_FLAGS_   += -k --verbose
MCXX_FLAGS_I_ = --instrument
MCXX_FLAGS_D_ = --debug -g
LDFLAGS_     = $(LDFLAGS)

SRCFILES = predict.cpp main.cpp
HDRFILES = predict.fpga.h predict.h smurff_const.h smurff_tb.h smurff_types.h
TOPDIRFILES = $(addprefix $(TOPDIR)/,$(SRCFILES) $(HDRFILES))
PROGRAM_ = predict
PROGS_   = $(PROGRAM_)-p $(PROGRAM_)-i $(PROGRAM_)-d

.PHONY: smp run boot clean

run: $(PROGS_)
	./$(PROGRAM_)-p
	./$(PROGRAM_)-d
	./$(PROGRAM_)-i

$(SRCFILES) $(HDRFILES): $(TOPDIRFILES)
	ln -sf $(TOPDIRFILES) ./

$(PROGRAM): $(SRCFILES) $(HDRFILES)
	$(CXX) $(CFLAGS_) $^ -o $@ $(LDFLAGS_)

$(PROGRAM_)-p: $(SRCFILES)
	$(MCXX) $(CFLAGS_) $(MCXX_FLAGS_) $^ -o $@ $(LDFLAGS_)

$(PROGRAM_)-i: $(SRCFILES)
	$(MCXX) $(CFLAGS_) $(MCXX_FLAGS_) $(MCXX_FLAGS_I_) $^ -o $@ $(LDFLAGS_)

$(PROGRAM_)-d: $(SRCFILES)
	$(MCXX) $(CFLAGS_) $(MCXX_FLAGS_) $(MCXX_FLAGS_D_) $^ -o $@ $(LDFLAGS_)

clean:
	rm -f *.o $(PROGS_) $(PROGRAM_)
	rm -f *.cpp *.h
	rm -rf zcu102
	rm -f *.backtrace.txt

