
PROGRAM_ = predict
SRCFILES = predict.cpp test_bench.cpp
HDRFILES = predict.fpga.h predict.h fxp.h observed_float.h
MODELFILES = vms_const.h vms_tb.h

SRCDIR = $(TOPDIR)/../../c++
MODELDIR= $(TOPDIR)/code

FULLSRCFILES  = $(addprefix $(SRCDIR)/,$(SRCFILES))
FULLHDRFILES  = $(addprefix $(SRCDIR)/,$(HDRFILES))
FULLMODELFILES = $(addprefix $(MODELDIR)/,$(MODELFILES))

DEPS = $(FULLSRCFILES) $(FULLHDRFILES) $(FULLMODELFILES)

CFLAGS_      = $(CFLAGS) -O0 -g -std=c++11 -I$(SRCDIR) -I$(MODELDIR)
LDFLAGS_     = $(LDFLAGS)


.PHONY: clean

clean:
	rm -f *.o $(PROGS_)
	rm -f $(PROGRAM_)_fp
	rm -f $(PROGRAM_)_fx
	rm -f *.cpp *.h
	rm -rf zcu102
	rm -f $(PROGRAM_).xtasks.config 
	rm -f $(PROGRAM_).bit 
	rm -f BOOT.BIN .
